# fly.toml app configuration file generated for nadario-seays on 2024-01-14T17:54:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nadario-seays"
primary_region = "atl"

[build]

[[mounts]]
  source = "db"
  destination = "/mnt/db"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
